package com.kingyee.project.mapper.bean;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;

@XStreamAlias("user2")
public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbggenerated  Mon Feb 10 17:15:44 CST 2014
	 */
	@XStreamAsAttribute
	@XStreamAlias("id2")
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.name
	 * @mbggenerated  Mon Feb 10 17:15:44 CST 2014
	 */
	@XStreamAlias("name2")
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.sex
	 * @mbggenerated  Mon Feb 10 17:15:44 CST 2014
	 */
	@XStreamAlias("sex2")
	private String sex;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbggenerated  Mon Feb 10 17:15:44 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbggenerated  Mon Feb 10 17:15:44 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.name
	 * @return  the value of user.name
	 * @mbggenerated  Mon Feb 10 17:15:44 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.name
	 * @param name  the value for user.name
	 * @mbggenerated  Mon Feb 10 17:15:44 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.sex
	 * @return  the value of user.sex
	 * @mbggenerated  Mon Feb 10 17:15:44 CST 2014
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.sex
	 * @param sex  the value for user.sex
	 * @mbggenerated  Mon Feb 10 17:15:44 CST 2014
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}
	
	public static void main(String[] args) throws Exception {
		User u = new User();
		u.setId(23);
		u.setName("hello");
		u.setSex("S");
		
		XStream xs = new XStream();
		xs.processAnnotations(User.class);
		System.out.println(xs.toXML(u));
		
		String s2 = "<user2 id2=\"23\"><name2>hello</name2><sex2>S</sex2></user2>";
		
		Object o = xs.fromXML(s2);
		System.out.println(o);
	}
}